"""
Automated UCC Report Email Sender (Cloud-hosted, Daily @ 6:00 PM IST)
-----------------------------------------------------------------------
Runs on GitHub Actions (not your local PC), so it fires every day even
if your computer is off. Steps:
    1. Reads UCC_Report.xlsx directly from this repository (update the
       file in GitHub whenever your data changes - no Google Drive
       access needed)
    2. Calculates Client-wise and Connection-wise Day-wise summaries
    3. Formats both as styled HTML tables and emails them automatically

All credentials (Gmail password, recipient list) are read from
environment variables, which GitHub Actions injects from repository
Secrets - nothing sensitive is hardcoded in this file.

Requirements:
    pip install pandas openpyxl

Author: Generated by Claude
"""

import smtplib
import sys
import os
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

import pandas as pd


# =============================================================
# ============  CONFIGURATION - EDIT THESE VALUES  ============
# =============================================================

CONFIG = {
    # --- Excel Source (file lives inside this repo; update it on GitHub whenever data changes) ---
    "EXCEL_FILE_PATH": "UCC_Report.xlsx",
    "SHEET_NAME": 0,

    # --- Raw data column names (matches your actual Excel headers) ---
    "COLUMNS": {
        "CLIENT": "clients",
        "CONNECTION": "connection",
        "COMPLAINT_NO": "Complaint no",
        "DATE_RAISED": "Date",
        "DAYS": "Days",          # Days-pending value already present in the sheet
    },

    # --- Email Settings (all pulled from environment variables / GitHub Secrets) ---
    "SMTP_SERVER": "smtp.gmail.com",
    "SMTP_PORT": 587,
    "SENDER_EMAIL": os.environ.get("SENDER_EMAIL", "dinesh.t@buzzworks.com"),
    "SENDER_PASSWORD": os.environ.get("SENDER_PASSWORD", "onop odwq yohs vxmi"),
    "RECEIVER_EMAILS": os.environ.get("RECEIVER_EMAILS", "jagadeesan.d@buzzworks.com").split(",") if os.environ.get("RECEIVER_EMAILS") else [],
    "CC_EMAILS": os.environ.get("CC_EMAILS", "").split(",") if os.environ.get("CC_EMAILS") else [],
    "SUBJECT": "UCC Daily Report - {date}",

    # --- Attachment ---
    "ATTACH_EXCEL": True,

    # --- Table Styling ---
    "HEADER_BG_COLOR": "#4472C4",
    "HEADER_TEXT_COLOR": "#FFFFFF",
    "TOTAL_ROW_BG_COLOR": "#D9D9D9",
    "ALERT_BG_COLOR": "#FF0000",       # Highlight color for "3 Days & Above"
    "ALERT_TEXT_COLOR": "#FFFFFF",
    "BORDER_COLOR": "#B0B0B0",
    "TABLE_FONT": "Arial, sans-serif",
    "TABLE_FONT_SIZE": "11px",

    # --- Email Body Extras ---
    "INTRO_TEXT": "Hi team,<br><br>Please find today's UCC report below.<br><br>",
    "OUTRO_TEXT": "<br>Regards,<br>Automated Reporting System",
}


# =============================================================
# ==================  DATA CALCULATION  =========================
# =============================================================

def read_raw_data(config):
    """Read the raw UCC data from Excel (all rows kept, including duplicate complaint numbers)."""
    path = config["EXCEL_FILE_PATH"]
    if not os.path.exists(path):
        raise FileNotFoundError(f"Excel file not found: {path}")

    df = pd.read_excel(path, sheet_name=config["SHEET_NAME"])
    df.columns = df.columns.str.strip()  # remove accidental leading/trailing spaces in headers
    cols = config["COLUMNS"]

    required = [cols["CLIENT"], cols["CONNECTION"], cols["COMPLAINT_NO"], cols["DAYS"]]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(
            f"Missing expected column(s) in Excel: {missing}\n"
            f"Available columns: {list(df.columns)}\n"
            f"Update CONFIG['COLUMNS'] to match your actual headers."
        )

    return df


def build_client_summary(df, config):
    """Table 1: Client-wise Count of UCC (with Total row)."""
    cols = config["COLUMNS"]
    summary = (
        df.groupby(cols["CLIENT"])[cols["COMPLAINT_NO"]]
        .count()
        .reset_index()
        .rename(columns={cols["COMPLAINT_NO"]: "Count of UCC"})
        .sort_values("Count of UCC", ascending=False)
    )
    total_row = pd.DataFrame({cols["CLIENT"]: ["Total"], "Count of UCC": [summary["Count of UCC"].sum()]})
    summary = pd.concat([summary, total_row], ignore_index=True)
    summary = summary.rename(columns={cols["CLIENT"]: "Clients"})
    return summary


def build_connection_summary(df, config):
    """Table 2: Connection-wise Day-wise Pending summary (uses the existing 'Days' column)."""
    cols = config["COLUMNS"]

    def bucket(d):
        try:
            d = int(d)
        except (ValueError, TypeError):
            return "Day 1"
        if d <= 1:
            return "Day 1"
        elif d == 2:
            return "Day 2"
        else:
            return "3 Days & Above"

    df = df.copy()
    df["_Bucket"] = df[cols["DAYS"]].apply(bucket)

    pivot = pd.pivot_table(
        df,
        index=cols["CONNECTION"],
        columns="_Bucket",
        values=cols["COMPLAINT_NO"],
        aggfunc="count",
        fill_value=0,
    )

    for col in ["Day 1", "Day 2", "3 Days & Above"]:
        if col not in pivot.columns:
            pivot[col] = 0
    pivot = pivot[["Day 1", "Day 2", "3 Days & Above"]]

    pivot["Count of Complaint no"] = pivot.sum(axis=1)
    pivot = pivot.reset_index().rename(columns={cols["CONNECTION"]: "Connections"})

    grand_total = pd.DataFrame({
        "Connections": ["Grand Total"],
        "Day 1": [pivot["Day 1"].sum()],
        "Day 2": [pivot["Day 2"].sum()],
        "3 Days & Above": [pivot["3 Days & Above"].sum()],
        "Count of Complaint no": [pivot["Count of Complaint no"].sum()],
    })
    pivot = pd.concat([pivot, grand_total], ignore_index=True)
    return pivot


# =============================================================
# ==================  HTML RENDERING  ===========================
# =============================================================

def render_client_table(df, config):
    """Render Table 1 (Client-wise Count of UCC) as HTML."""
    header_bg = config["HEADER_BG_COLOR"]
    header_color = config["HEADER_TEXT_COLOR"]
    total_bg = config["TOTAL_ROW_BG_COLOR"]
    border = config["BORDER_COLOR"]
    font_family = config["TABLE_FONT"]
    font_size = config["TABLE_FONT_SIZE"]

    html = f"""
    <table style="border-collapse: collapse; font-family: {font_family}; font-size: {font_size}; border: 1px solid {border};">
        <tr>
            <th style="background-color:{header_bg}; color:{header_color}; padding:5px 8px; border:1px solid {border}; text-align:center;">Clients</th>
            <th style="background-color:{header_bg}; color:{header_color}; padding:5px 8px; border:1px solid {border}; text-align:center;">Count of UCC</th>
        </tr>
    """
    for _, row in df.iterrows():
        is_total = row["Clients"] == "Total"
        bg = total_bg if is_total else "#FFFFFF"
        weight = "bold" if is_total else "normal"
        html += f"""
        <tr style="background-color:{bg}; font-weight:{weight};">
            <td style="padding:4px 8px; border:1px solid {border};">{row['Clients']}</td>
            <td style="padding:4px 8px; border:1px solid {border}; text-align:center;">{row['Count of UCC']}</td>
        </tr>
        """
    html += "</table>"
    return html


def render_connection_table(df, config):
    """Render Table 2 (Connection-wise Day-wise Pending) as HTML."""
    header_bg = config["HEADER_BG_COLOR"]
    header_color = config["HEADER_TEXT_COLOR"]
    total_bg = config["TOTAL_ROW_BG_COLOR"]
    alert_bg = config["ALERT_BG_COLOR"]
    alert_color = config["ALERT_TEXT_COLOR"]
    border = config["BORDER_COLOR"]
    font_family = config["TABLE_FONT"]
    font_size = config["TABLE_FONT_SIZE"]

    html = f"""
    <table style="border-collapse: collapse; font-family: {font_family}; font-size: {font_size}; border: 1px solid {border};">
        <tr>
            <th rowspan="2" style="background-color:{header_bg}; color:{header_color}; padding:5px 8px; border:1px solid {border}; text-align:center;">Connections</th>
            <th colspan="3" style="background-color:{header_bg}; color:{header_color}; padding:5px 8px; border:1px solid {border}; text-align:center;">UCC Pending Day wise</th>
            <th rowspan="2" style="background-color:{header_bg}; color:{header_color}; padding:5px 8px; border:1px solid {border}; text-align:center;">Count of Complaint no</th>
        </tr>
        <tr>
            <th style="background-color:{header_bg}; color:{header_color}; padding:4px 6px; border:1px solid {border}; text-align:center;">(Day 1)</th>
            <th style="background-color:{header_bg}; color:{header_color}; padding:4px 6px; border:1px solid {border}; text-align:center;">(Day 2)</th>
            <th style="background-color:{alert_bg}; color:{alert_color}; padding:4px 6px; border:1px solid {border}; text-align:center;">3 Days &amp; Above</th>
        </tr>
    """
    for _, row in df.iterrows():
        is_total = row["Connections"] == "Grand Total"
        bg = total_bg if is_total else "#FFFFFF"
        weight = "bold" if is_total else "normal"

        def cell(val):
            return val if val != 0 else "-"

        html += f"""
        <tr style="background-color:{bg}; font-weight:{weight};">
            <td style="padding:4px 8px; border:1px solid {border};">{row['Connections']}</td>
            <td style="padding:4px 8px; border:1px solid {border}; text-align:center;">{cell(row['Day 1'])}</td>
            <td style="padding:4px 8px; border:1px solid {border}; text-align:center;">{cell(row['Day 2'])}</td>
            <td style="padding:4px 8px; border:1px solid {border}; text-align:center;">{cell(row['3 Days & Above'])}</td>
            <td style="padding:4px 8px; border:1px solid {border}; text-align:center;">{row['Count of Complaint no']}</td>
        </tr>
        """
    html += "</table>"
    return html


def build_email_html(client_table_html, connection_table_html, config):
    now = datetime.now()
    today = now.strftime("%d-%b-%Y")
    timestamp = now.strftime("%d-%b-%Y %I:%M %p")
    body = f"""
    <html>
    <body style="font-family: {config['TABLE_FONT']}; color: #333333;">
        {config['INTRO_TEXT']}
        <p style="font-size:12px; color:#666666;">Report generated on: {timestamp}</p>
        <p><b>UCC Pending Day-wise (Connection-wise)</b></p>
        {connection_table_html}
        <br><br>
        <p><b>Client-wise Count of UCC</b></p>
        {client_table_html}
        {config['OUTRO_TEXT']}
    </body>
    </html>
    """
    return body, today, now.strftime("%I:%M %p")


# =============================================================
# ==================  EMAIL SENDING  =============================
# =============================================================

def send_email(html_body, subject, config):
    msg = MIMEMultipart("mixed")
    msg["From"] = config["SENDER_EMAIL"]
    msg["To"] = ", ".join(config["RECEIVER_EMAILS"])
    if config["CC_EMAILS"]:
        msg["Cc"] = ", ".join(config["CC_EMAILS"])
    msg["Subject"] = subject

    msg.attach(MIMEText(html_body, "html"))

    if config["ATTACH_EXCEL"]:
        file_path = config["EXCEL_FILE_PATH"]
        if os.path.exists(file_path):
            with open(file_path, "rb") as f:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(f.read())
            encoders.encode_base64(part)
            filename = os.path.basename(file_path)
            part.add_header("Content-Disposition", f"attachment; filename={filename}")
            msg.attach(part)
        else:
            print(f"Warning: attachment file not found, skipping: {file_path}")

    all_recipients = config["RECEIVER_EMAILS"] + config["CC_EMAILS"]

    try:
        with smtplib.SMTP(config["SMTP_SERVER"], config["SMTP_PORT"]) as server:
            server.starttls()
            server.login(config["SENDER_EMAIL"], config["SENDER_PASSWORD"])
            server.sendmail(config["SENDER_EMAIL"], all_recipients, msg.as_string())
        print(f"[{datetime.now()}] Email sent successfully!")
    except smtplib.SMTPAuthenticationError:
        print("ERROR: Authentication failed. Check email/password (use an App Password for Gmail).")
    except Exception as e:
        print(f"ERROR: Failed to send email -> {e}")


# =============================================================
# =====================  MAIN JOB  ================================
# =============================================================

def run_report_job():
    """The full pipeline: read data -> calculate -> render -> send."""
    try:
        print(f"[{datetime.now()}] Starting UCC report job...")
        df = read_raw_data(CONFIG)

        client_summary = build_client_summary(df, CONFIG)
        connection_summary = build_connection_summary(df, CONFIG)

        client_html = render_client_table(client_summary, CONFIG)
        connection_html = render_connection_table(connection_summary, CONFIG)

        email_html, today, time_now = build_email_html(client_html, connection_html, CONFIG)
        subject = CONFIG["SUBJECT"].format(date=today)

        send_email(email_html, subject, CONFIG)
    except Exception as e:
        print(f"ERROR in report job: {e}")
        sys.exit(1)


if __name__ == "__main__":
    run_report_job()
