name: UCC Daily Report

on:
  schedule:
     - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run UCC report script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
          CC_EMAILS: ${{ secrets.CC_EMAILS }}
        run: python ucc_daily_report.py
